# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adastra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
