# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adastra', '0002_auto_20180619_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRelationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'IN WORK'), (2, 'DONE')]),
        ),
        migrations.AddField(
            model_name='taskrelationmodel',
            name='task_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_from', to='adastra.TaskModel'),
        ),
        migrations.AddField(
            model_name='taskrelationmodel',
            name='task_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_to', to='adastra.TaskModel'),
        ),
    ]
