# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 19:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adastra', '0003_auto_20180621_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('last_created', models.DateField()),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adastra.TaskListModel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPatternModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('status', models.IntegerField(choices=[(0, 'CREATED'), (1, 'IN WORK'), (2, 'DONE')])),
                ('priority', models.IntegerField(choices=[(0, 'LOW'), (1, 'MIDDLE'), (2, 'HIGH')])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='planmodel',
            name='task_pattern',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adastra.TaskPatternModel'),
        ),
    ]
