# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adastra', '0004_auto_20180621_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='delta',
            field=models.IntegerField(choices=[(0, 'DAILY'), (1, 'WEEKLY'), (2, 'MONTHLY'), (3, 'YEARLY')]),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
